spec <- cols(
  `Analysis ID` = col_double(),
  `Analysis name` = col_character(),
  `Strata ID` = col_double(),
  `Strata name` = col_character(),
  `Cohort ID` = col_double(),
  `Cohort name` = col_character(),
  `Covariate ID` = col_double(),
  `Covariate name` = col_character(),
  `Covariate short name` = col_character(),
  `Value field` = col_double(),
  `Missing Means Zero` = col_double(),
  Count = col_double(),
  Percent = col_double(),
  Avg = col_double(),
  StdDev = col_double(),
  Min = col_double(),
  P10 = col_double(),
  P25 = col_double(),
  Median = col_double(),
  P75 = col_double(),
  P90 = col_double(),
  Max = col_double()
)